### ISSUE TITLE
Error on recursive dryrun

### ISSUE THREAD

**Issue by automatonic** [dylansmith/node-exif-renamer#1]
I have a massive set of JPGs that I was hoping to utilize this project on. It has all the stuff I am likely to need: (EXIF data, templated directory/file rename, preview of changes, etc.)

So I installed the app via NPM and installed it globally, then tried:

`exif-renamer imagesDirectory/ -d -r`                         

I was hoping for a listing of all the included renames so that I could start crafting a renaming template.

Unfortunately, what I got was:

```
/volume1/@appstore/Node.js/usr/lib/node_modules/exif-renamer/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: boolean is not a function
    at /volume1/@appstore/Node.js/usr/lib/node_modules/exif-renamer/lib/exif-renamer.js:272:13
    at _fulfilled (/volume1/@appstore/Node.js/usr/lib/node_modules/exif-renamer/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/volume1/@appstore/Node.js/usr/lib/node_modules/exif-renamer/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/volume1/@appstore/Node.js/usr/lib/node_modules/exif-renamer/node_modules/q/q.js:749:13)
    at /volume1/@appstore/Node.js/usr/lib/node_modules/exif-renamer/node_modules/q/q.js:509:49
    at flush (/volume1/@appstore/Node.js/usr/lib/node_modules/exif-renamer/node_modules/q/q.js:108:17)
    at process._tickDomainCallback (node.js:463:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

Looks like the callback is failing on the completion of the recursive promises...somehow its getting a bad callback? getting passed a boolean instead of a function?

**Comment by dylansmith** [comment]
Hi, thanks for raising an issue - I'll try to take a look at it in the next few days.

**Comment by dylansmith** [comment]
I've just pushed v0.6.1 which fixes this issue. Let me know how you get on.

**Comment by automatonic** [comment]
That got me past the initial error, but now I have further problems. That said, it very well could be the way the box is set up...and the data involved. I am getting a date parse error now, but i am pretty sure that is my exif data. This problem appears to be solved. Thanks for your time!

**Comment by dylansmith** [comment]
Hey, I think this might be an issue with the exif library I am using - when I first wrote this it was the best available, but maybe I need to look around again. Can you provide the stacktrace of the error?
