### ISSUE TITLE
exif-renamer uses the wrong time for ctime fallback on Mac

### ISSUE THREAD

**Issue by bbugh** [dylansmith/node-exif-renamer#10]
I have some files that don't have exif data but have the correct Mac created time. However, `exif-renamer` is using the wrong `stat` value (at least for Mac) to get the created time.

Using Mac's built-in `GetFileInfo` command, you can see here that the created time is as expect (05/04): 

```
GetFileInfo IMG_2708.JPG
file: "IMG_2708.JPG"
...
created: 05/04/2017 14:55:07   # correct, expected time
modified: 05/04/2017 14:55:07
```

However, the stat in `lib/exif-renamer.js:173` results in this:

```
# util.inspect(src.stat);
Ctime is Stats {
  ...,
  atimeMs: 1511456562000,
  mtimeMs: 1493927707000,
  ctimeMs: 1511454878000,
  birthtimeMs: 1493927707000,
  atime: 2017-11-23T17:02:42.000Z,
  mtime: 2017-05-04T19:55:07.000Z,
  ctime: 2017-11-23T16:34:38.000Z,          # not correct
  birthtime: 2017-05-04T19:55:07.000Z }     # correct, expected time
```

The ctime here is what Mac uses as "Date Added" which was created by `cp -p`, which preserves `ctime` (which Mac stores in `birthtime`).

Here's what it looks like in Finder:

![image](https://user-images.githubusercontent.com/438465/33183725-9d6beb54-d03e-11e7-83d2-4e8804efff6d.png)

I was able to fix this by changing it to use `birthtime` as the fallback instead of `ctime`. I know Mac stores different times and such, but I don't know the implications of this on other platforms. 

```diff
173,174c173,174
<             else if (this.config.fallback_ctime === true && src.stat && src.stat.ctime) {
<                 datetime = src.stat.ctime;
---
>             else if (this.config.fallback_ctime === true && src.stat && src.stat.birthtime) {
>                 datetime = src.stat.birthtime;
```

**Comment by dylansmith** [comment]
Hey @bbugh, thanks for the thorough description of the issue. I'll look into it when I get a spare moment.

**Comment by dylansmith** [comment]
@bbugh can you checkout this branch and see if this fixes your issue?

**Comment by bbugh** [comment]
This works perfectly! Thank you so much for fixing this.

**Comment by dylansmith** [comment]
Great, I'll bump the version and release it
