### ISSUE TITLE
Consider allowing any file type

### ISSUE THREAD

**Issue by bbugh** [dylansmith/node-exif-renamer#12]
We have some `.gif` and `.m4v` files that we'd like to name with the same naming pattern as the other files. They obviously don't have EXIF data, but given that the tool can fall back on creation time, it would be nice if it could process any file. I was able to get this to work by commenting out the file extension check and verifying that exif_data was set, so it was an easy change.

**Comment by bbugh** [comment]
PS this tool is awesome, thank you so much for making it!

**Comment by dylansmith** [comment]
Nice idea, should be simple to do.

**Comment by dylansmith** [comment]
@bbugh I realised this is already supported if you use the `valid_extensions` config option.

**Comment by bbugh** [comment]
Ah ha! Thanks for pointing that out.
