### ISSUE TITLE
Research command line template argument/s (-t)

### ISSUE THREAD

**Issue by ldexterldesign** [dylansmith/node-exif-renamer#7]
Hey,

Could you offer some documentation on using the ```-t``` argument via command line?

I'd like to specify custom file names, beyond the default

Yours hopefully

**Comment by dylansmith** [comment]
Hi! What kind of documentation are you specifically interested in? As a quick example of usage, you can try to run the following command from your local copy of the repository:

```bash
./bin/exif-renamer -t './{{datetime "yyyy-mm"}}:{{file}}' -d demo/img/exif.jpg
```

This shows how you would pass a quoted template string using the `-t` argument. I posted some docs on the format of the template string in [the readme](/dylansmith/node-exif-renamer/blob/master/README.md), but perhaps if you can tell me about your requirements I could be more helpful?

**Comment by ldexterldesign** [comment]
Thanks for reply

Need to batch process some image files

Now having problem with the file name extensions - can I ignore them when using ```-t```?

Thanks

**Comment by dylansmith** [comment]
Yes, that is possible. The template controls all aspects of the filename.For example, the following will generate a file without an extension:

```bash
./bin/exif-renamer -t './{{datetime "yyyy-mm"}}:{{name}}' -d demo/img/exif.jpg
```

Take a look at the metadata section of the readme for all the available variables.

**Comment by ldexterldesign** [comment]
Thank you!

**Comment by dylansmith** [comment]
No problem. Hope you enjoy using this tool (it would be awesome if you could star it if you do)!

**Comment by ldexterldesign** [comment]
Sorry, "ignore" the extension, as in leave it/them intact

I don't need to mess with the extension

Cheers

**Comment by ldexterldesign** [comment]
```
exif-renamer -t '{{datetime}}.{{ext}}' -d 
```

Apologies, I'm with you now ;)

Regards

**Comment by ldexterldesign** [comment]
Is there comprehensive documentation on the metadata, something along the lines of: https://www.npmjs.com/package/exif

Yours hopefully

**Comment by ldexterldesign** [comment]
```
exif-renamer -e IMG_20150312_013213.jpg
```

Hehe, sorry for the noise - I may as well be writing the documentation at this rate :/

Apologies,

**Comment by ldexterldesign** [comment]
~ https://twitter.com/ldexterldesign/status/582664682185576448

**Comment by dylansmith** [comment]
Thanks very much Lewis, I'll include your `-e` recommendation in the readme.

**Comment by dylansmith** [comment]
Hi Lewis, I have [added a new `-l` switch](https://github.com/dylansmith/node-exif-renamer/commit/2ccfa645b43d5ea254cec5bacdf809239aeb6977) which lists all the metadata passed to the templating function.
