### ISSUE TITLE
Ability to handle existing filename would be very valuable

### ISSUE THREAD

**Issue by TotallyInformation** [dylansmith/node-exif-renamer#9]
Hi, Just started trying to use your library to handle my needs for renaming camera files for archiving.

However, I'm already discovering that I will need a custom rename function. The hardest part of that will be to handle file renames that cause a clash. For example, I rename using the following template:

    {{datetime}}-{{exif.Model}}.{{ext}}

But photos taken within a second of each other will cause a clashing name. Normally I resolve that by adding an increment to the end but I only want that increment if there is actually a clash.

Would it be possible to extend this library to include a name clash resolution template as well as the standard template? That would need to cope with multiple clashes so an autoincrementing number would be needed as one of the template options.

Incidentally, one of the other issues I have is that some camera's may not have their date/time set correctly. As such, any EXIF date prior to 1990 is unlikely to be valid and should probably raise an exception.

Many thanks for this useful library.
Regards, Julian.

**Comment by dylansmith** [comment]
Hey Julian

Regarding the clashing filenames: that's a great point, I'll look at including something asap.

For the pre-1990 datetimes, would you want it to raise an exception (i.e. stop processing any further images) or would you rather provide a way of dealing with it (ignore, warn, etc)?

Thanks
Dylan

**Comment by TotallyInformation** [comment]
Hi Dylan, thanks for the response.

For the datetimes, it would be nice to have an option to skip the file with a warning but the default should be to fail I think? Because renaming loads of files with the date/time an not realising all the data is wrong could be quite devastating. On the other hand, if you are not using the date/time in a rename, you should be able to ignore the issue.

While I have you "on the line" :)  some filters for the directory function would be nice! Or being able to use globbing in the file name for the rename function? Being able to restrict to a file pattern would save the effort of doing it ourselves since the folder might also contain PDF, TXT, video and other files that shouldn't be processed. Or might just contain some files I don't want processing so I might want to process something like:

    DSC????.JPG

or

   img*.jpg

Great tool though and the best so far of the Node.JS exif tools. Thanks.

**Comment by TotallyInformation** [comment]
Oops, pressed the wrong button!

**Comment by dylansmith** [comment]
Update: haven't forgotten about this. Hoping to get some time in the next 2 weeks to address it. I appreciate your patience.

**Comment by dylansmith** [comment]
I know, I suck. But I'm still planning to look at this.

**Comment by dylansmith** [comment]
@TotallyInformation can you take a look at https://github.com/dylansmith/node-exif-renamer/tree/1.2.0 and see if it solves your issues?
